services:
    david63.logconnections.listener:
        class: david63\logconnections\event\listener
        arguments:
            - '@config'		
            - '@log'
            - '@user'
            - '@auth'
        tags:
            - { name: event.listener }

    david63.logconnections.admin.controller:
        class: david63\logconnections\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@language'
